// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkbCOAjcMNkYod-HAvJPhY86il3DqBWg0',
    appId: '1:11672111632:web:18227f545a6324f56d9895',
    messagingSenderId: '11672111632',
    projectId: 'morning-buddies-e8db1',
    authDomain: 'morning-buddies-e8db1.firebaseapp.com',
    storageBucket: 'morning-buddies-e8db1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuKADh1CtsksFrCI3gd3LmqPQ32FykzOk',
    appId: '1:11672111632:android:ea06d4098cb7a0d96d9895',
    messagingSenderId: '11672111632',
    projectId: 'morning-buddies-e8db1',
    storageBucket: 'morning-buddies-e8db1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw8RMw2JY47CX45XeDoZV-RWBzV2Sd3iI',
    appId: '1:11672111632:ios:828de8c7f9e9cd726d9895',
    messagingSenderId: '11672111632',
    projectId: 'morning-buddies-e8db1',
    storageBucket: 'morning-buddies-e8db1.appspot.com',
    iosBundleId: 'com.example.morningBuddies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw8RMw2JY47CX45XeDoZV-RWBzV2Sd3iI',
    appId: '1:11672111632:ios:828de8c7f9e9cd726d9895',
    messagingSenderId: '11672111632',
    projectId: 'morning-buddies-e8db1',
    storageBucket: 'morning-buddies-e8db1.appspot.com',
    iosBundleId: 'com.example.morningBuddies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkbCOAjcMNkYod-HAvJPhY86il3DqBWg0',
    appId: '1:11672111632:web:7775ebe839ccf99a6d9895',
    messagingSenderId: '11672111632',
    projectId: 'morning-buddies-e8db1',
    authDomain: 'morning-buddies-e8db1.firebaseapp.com',
    storageBucket: 'morning-buddies-e8db1.appspot.com',
  );

}